import diffResults from '../reports/diff.json'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

type HomeProps = {
  created: string[];
  modified: string[];
  deleted: string[];
}

export async function getStaticProps() {
  return {
    props: diffResults
  }
}

const Home: NextPage<HomeProps> = ({created, modified, deleted}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pull Request Visualizar</title>
        <meta name="description" content="Generated by Pull Request Visualizar Action" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          PR Preview: asdasd
        </h1>
        <div className={styles.grid}>
          <div>
          <div>Files Created</div>
          {created.map(fileCreated => <div key={fileCreated}>{fileCreated}</div>)}
          </div>
          <div>
          <div>Files Modified</div>
          {modified.map(fileModified => <div key={fileModified}>{fileModified}</div>)}
          </div>
          <div>
          <div>Files Deleted</div>
          {deleted.map(fileDeleted => <div key={fileDeleted}>{fileDeleted}</div>)}
          </div>
        </div>
      </main>
</div>);
}

export default Home
